## 部署
- name: OwnCloud
  hosts: all
  become: yes
  become_method: sudo 
  vars_files:
    - vars/main.yml 
  vars_prompt:
    - name: 'webs_selection'
      prompt: "\nWhich Web-Server do you want to use? [ 1/2 ] \n\n
      1: Apache\n
      2: Nginx\n"
      private: no
      default: 1

  vars:

    webs_select:
      '1': 'apache'
      '2': 'nginx'

    infrastructure_select:
      '1': 'LAMP'
      '2': 'LNMP'
      
    runtime_name: "{{infrastructure_select[webs_selection] | lower}}" 
    owncloud_webs: "{{webs_select[webs_selection]}}" 
    w9panel_webs: "{{webs_select[webs_selection]}}" 

    w9panel_set_infrastructure: "{{infrastructure_select[webs_selection]}}" 
    w9panel_set_apps: 
      - OwnCloud
    
  pre_tasks:
    - debug:
        msg: OwnCloud will be installed on {{w9panel_set_infrastructure}}, OS is {{ansible_distribution}}

  roles:

    - {role: owncloud, tags: "owncloud"}
    - {role: role_init, tags: "role_init"}
    - {role: role_preend, tags: "role_preend"}
    - {role: role_end, tags: "end"}
