#Moodle版本，需定期维护
owncloud_version: v10.4.1

#Web服务器：apache | nginx，通过交互式选择获取
owncloud_webs: apache

owncloud_vhost_dir: /etc/httpd/vhost
owncloud_vhost_src: vhost.conf
owncloud_service: httpd
owncloud_db_password: "123456"
owncloud_owner: apache
owncloud_name: "owncloud"
owncloud_title: "OwnCloud"
#下载链接需定期维护
owncloud_download_url: "https://download.owncloud.org/download/community/owncloud-latest.zip"

